# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ips_protocol/positions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ips_protocol/positions.proto',
  package='ips.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1cips_protocol/positions.proto\x12\tips.proto\"\xe0\x01\n\x0eGlobalPosition\x12\t\n\x01t\x18\x01 \x02(\x01\x12\x10\n\x08latitude\x18\x02 \x02(\x01\x12\x11\n\tlongitude\x18\x03 \x02(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x01\x12\x19\n\x11\x61ltitude_accuracy\x18\x06 \x01(\x01\x12\r\n\x05speed\x18\x07 \x01(\x01\x12\x16\n\x0espeed_accuracy\x18\x08 \x01(\x01\x12\x0f\n\x07heading\x18\t \x01(\x01\x12\x18\n\x10\x64\x65vice_timestamp\x18\n \x01(\x01\x12\r\n\x05\x66loor\x18\x0b \x01(\x03\"\x9f\x02\n\x08Position\x12\r\n\x01t\x18\x01 \x01(\x01\x42\x02\x18\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\r\n\x05\x66loor\x18\x04 \x01(\x03\x12\x0b\n\x03sx2\x18\x05 \x01(\x01\x12\x0b\n\x03sy2\x18\x06 \x01(\x01\x12\x0b\n\x03sxy\x18\x07 \x01(\x01\x12%\n\x04type\x18\x08 \x02(\x0e\x32\x17.ips.proto.PositionType\x12\x10\n\x08\x61\x63\x63uracy\x18\t \x01(\x01\x12\r\n\x05\x64\x65lay\x18\n \x01(\x01\x12\x11\n\tt_created\x18\x0b \x01(\x01\x12\r\n\x05t_est\x18\x0c \x01(\x01\x12)\n\x08\x61ncestor\x18\r \x01(\x0e\x32\x17.ips.proto.PositionType\x12\x10\n\x08latitude\x18\x0e \x01(\x01\x12\x11\n\tlongitude\x18\x0f \x01(\x01*\xfc\x01\n\x0cPositionType\x12\x07\n\x03KNN\x10\x00\x12\x10\n\x0cGROUND_TRUTH\x10\x01\x12\t\n\x05\x46INAL\x10\x02\x12\n\n\x06KALMAN\x10\x03\x12\x08\n\x04SLAM\x10\x04\x12\x08\n\x04\x46LIP\x10\x05\x12\x07\n\x03\x41KF\x10\x06\x12\r\n\tSLAM_GRID\x10\x07\x12\x0c\n\x08SLAM_MAP\x10\t\x12\x0e\n\nSLAM_GRAPH\x10\n\x12\x07\n\x03GPS\x10\x0b\x12\r\n\tRADIO_BLE\x10\x0c\x12\x0e\n\nRADIO_WIFI\x10\r\x12\x12\n\x0eRADIO_WIFI_BLE\x10\x0e\x12\r\n\tPROXIMITY\x10\x0f\x12\t\n\x05\x41PPLE\x10\x10\x12\x0c\n\x08SELECTED\x10\x11\x12\x0c\n\x07UNKNOWN\x10\xff\x01')
)

_POSITIONTYPE = _descriptor.EnumDescriptor(
  name='PositionType',
  full_name='ips.proto.PositionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KNN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUND_TRUTH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KALMAN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLAM', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLIP', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AKF', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLAM_GRID', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLAM_MAP', index=8, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLAM_GRAPH', index=9, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS', index=10, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RADIO_BLE', index=11, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RADIO_WIFI', index=12, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RADIO_WIFI_BLE', index=13, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROXIMITY', index=14, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLE', index=15, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELECTED', index=16, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=17, number=255,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=561,
  serialized_end=813,
)
_sym_db.RegisterEnumDescriptor(_POSITIONTYPE)

PositionType = enum_type_wrapper.EnumTypeWrapper(_POSITIONTYPE)
KNN = 0
GROUND_TRUTH = 1
FINAL = 2
KALMAN = 3
SLAM = 4
FLIP = 5
AKF = 6
SLAM_GRID = 7
SLAM_MAP = 9
SLAM_GRAPH = 10
GPS = 11
RADIO_BLE = 12
RADIO_WIFI = 13
RADIO_WIFI_BLE = 14
PROXIMITY = 15
APPLE = 16
SELECTED = 17
UNKNOWN = 255



_GLOBALPOSITION = _descriptor.Descriptor(
  name='GlobalPosition',
  full_name='ips.proto.GlobalPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.GlobalPosition.t', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ips.proto.GlobalPosition.latitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ips.proto.GlobalPosition.longitude', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='ips.proto.GlobalPosition.accuracy', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ips.proto.GlobalPosition.altitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_accuracy', full_name='ips.proto.GlobalPosition.altitude_accuracy', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ips.proto.GlobalPosition.speed', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_accuracy', full_name='ips.proto.GlobalPosition.speed_accuracy', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='ips.proto.GlobalPosition.heading', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_timestamp', full_name='ips.proto.GlobalPosition.device_timestamp', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floor', full_name='ips.proto.GlobalPosition.floor', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=268,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='ips.proto.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Position.t', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ips.proto.Position.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ips.proto.Position.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floor', full_name='ips.proto.Position.floor', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sx2', full_name='ips.proto.Position.sx2', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sy2', full_name='ips.proto.Position.sy2', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sxy', full_name='ips.proto.Position.sxy', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ips.proto.Position.type', index=7,
      number=8, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='ips.proto.Position.accuracy', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay', full_name='ips.proto.Position.delay', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_created', full_name='ips.proto.Position.t_created', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_est', full_name='ips.proto.Position.t_est', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ancestor', full_name='ips.proto.Position.ancestor', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ips.proto.Position.latitude', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ips.proto.Position.longitude', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=558,
)

_POSITION.fields_by_name['type'].enum_type = _POSITIONTYPE
_POSITION.fields_by_name['ancestor'].enum_type = _POSITIONTYPE
DESCRIPTOR.message_types_by_name['GlobalPosition'] = _GLOBALPOSITION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.enum_types_by_name['PositionType'] = _POSITIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalPosition = _reflection.GeneratedProtocolMessageType('GlobalPosition', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALPOSITION,
  __module__ = 'ips_protocol.positions_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.GlobalPosition)
  ))
_sym_db.RegisterMessage(GlobalPosition)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'ips_protocol.positions_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Position)
  ))
_sym_db.RegisterMessage(Position)


_POSITION.fields_by_name['t']._options = None
# @@protoc_insertion_point(module_scope)
