# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ips_protocol/sensors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ips_protocol/sensors.proto',
  package='ips.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1aips_protocol/sensors.proto\x12\tips.proto\"I\n\x06Sensor\x12\t\n\x01t\x18\x01 \x02(\x01\x12\t\n\x01x\x18\x02 \x02(\x01\x12\t\n\x01y\x18\x03 \x02(\x01\x12\t\n\x01z\x18\x04 \x02(\x01\x12\x13\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x01:\x01\x31\"<\n\x07\x43ontext\x12\t\n\x01t\x18\x01 \x02(\x01\x12\x12\n\nidentifier\x18\x02 \x02(\x03\x12\x12\n\nconfidence\x18\x03 \x02(\x03\" \n\x08Pressure\x12\t\n\x01t\x18\x01 \x02(\x01\x12\t\n\x01v\x18\x02 \x02(\x01\"\xb4\x01\n\x04Step\x12\t\n\x01t\x18\x01 \x02(\x01\x12\x0e\n\x06length\x18\x02 \x02(\x01\x12\x12\n\nvar_length\x18\x03 \x02(\x01\x12\x0f\n\x07heading\x18\x04 \x01(\x01\x12\x13\n\x0bvar_heading\x18\x05 \x01(\x01\x12\x13\n\x07max_acc\x18\x06 \x01(\x01\x42\x02\x18\x01\x12\x10\n\x08\x64uration\x18\x07 \x01(\x01\x12\x15\n\rdelta_heading\x18\x08 \x01(\x01\x12\x19\n\x11var_delta_heading\x18\t \x01(\x01\"a\n\x05Radio\x12\"\n\x04type\x18\x01 \x02(\x0e\x32\x14.ips.proto.RadioType\x12\t\n\x01t\x18\x02 \x02(\x01\x12\x0c\n\x04ssid\x18\x03 \x02(\t\x12\r\n\x05\x62ssid\x18\x04 \x02(\x03\x12\x0c\n\x04rssi\x18\x05 \x02(\x03\"\xa2\x01\n\x0bOrientation\x12(\n\x04type\x18\x01 \x02(\x0e\x32\x1a.ips.proto.OrientationType\x12\t\n\x01t\x18\x02 \x01(\x01\x12\x0c\n\x04roll\x18\x03 \x01(\x01\x12\x10\n\x08roll_var\x18\x04 \x01(\x01\x12\r\n\x05pitch\x18\x05 \x01(\x01\x12\x11\n\tpitch_var\x18\x06 \x01(\x01\x12\x0b\n\x03yaw\x18\x07 \x01(\x01\x12\x0f\n\x07yaw_var\x18\x08 \x01(\x01*d\n\tRadioType\x12\x08\n\x04WIFI\x10\x00\x12\x07\n\x03GSM\x10\x01\x12\x07\n\x03UKW\x10\x02\x12\r\n\tBLUETOOTH\x10\x03\x12\x10\n\x0c\x42LUETOOTH_LE\x10\x04\x12\x0b\n\x07IBEACON\x10\x05\x12\r\n\tUNDEFINED\x10\x06*m\n\x0fOrientationType\x12\x16\n\x12\x44\x45VICE_ORIENTATION\x10\x00\x12\x13\n\x0fPDR_ORIENTATION\x10\x01\x12\x16\n\x12KALMAN_ORIENTATION\x10\x02\x12\x15\n\x11\x46INAL_ORIENTATION\x10\x03')
)

_RADIOTYPE = _descriptor.EnumDescriptor(
  name='RadioType',
  full_name='ips.proto.RadioType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIFI', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GSM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UKW', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUETOOTH', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUETOOTH_LE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IBEACON', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=659,
  serialized_end=759,
)
_sym_db.RegisterEnumDescriptor(_RADIOTYPE)

RadioType = enum_type_wrapper.EnumTypeWrapper(_RADIOTYPE)
_ORIENTATIONTYPE = _descriptor.EnumDescriptor(
  name='OrientationType',
  full_name='ips.proto.OrientationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE_ORIENTATION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PDR_ORIENTATION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KALMAN_ORIENTATION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINAL_ORIENTATION', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=761,
  serialized_end=870,
)
_sym_db.RegisterEnumDescriptor(_ORIENTATIONTYPE)

OrientationType = enum_type_wrapper.EnumTypeWrapper(_ORIENTATIONTYPE)
WIFI = 0
GSM = 1
UKW = 2
BLUETOOTH = 3
BLUETOOTH_LE = 4
IBEACON = 5
UNDEFINED = 6
DEVICE_ORIENTATION = 0
PDR_ORIENTATION = 1
KALMAN_ORIENTATION = 2
FINAL_ORIENTATION = 3



_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='ips.proto.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Sensor.t', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ips.proto.Sensor.x', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ips.proto.Sensor.y', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ips.proto.Sensor.z', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='ips.proto.Sensor.accuracy', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=114,
)


_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='ips.proto.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Context.t', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='ips.proto.Context.identifier', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ips.proto.Context.confidence', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=176,
)


_PRESSURE = _descriptor.Descriptor(
  name='Pressure',
  full_name='ips.proto.Pressure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Pressure.t', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='ips.proto.Pressure.v', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=210,
)


_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='ips.proto.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Step.t', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='ips.proto.Step.length', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_length', full_name='ips.proto.Step.var_length', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='ips.proto.Step.heading', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_heading', full_name='ips.proto.Step.var_heading', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_acc', full_name='ips.proto.Step.max_acc', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='ips.proto.Step.duration', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta_heading', full_name='ips.proto.Step.delta_heading', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_delta_heading', full_name='ips.proto.Step.var_delta_heading', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=393,
)


_RADIO = _descriptor.Descriptor(
  name='Radio',
  full_name='ips.proto.Radio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ips.proto.Radio.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Radio.t', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssid', full_name='ips.proto.Radio.ssid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bssid', full_name='ips.proto.Radio.bssid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='ips.proto.Radio.rssi', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=492,
)


_ORIENTATION = _descriptor.Descriptor(
  name='Orientation',
  full_name='ips.proto.Orientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ips.proto.Orientation.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='ips.proto.Orientation.t', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='ips.proto.Orientation.roll', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll_var', full_name='ips.proto.Orientation.roll_var', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='ips.proto.Orientation.pitch', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_var', full_name='ips.proto.Orientation.pitch_var', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='ips.proto.Orientation.yaw', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw_var', full_name='ips.proto.Orientation.yaw_var', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=657,
)

_RADIO.fields_by_name['type'].enum_type = _RADIOTYPE
_ORIENTATION.fields_by_name['type'].enum_type = _ORIENTATIONTYPE
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['Pressure'] = _PRESSURE
DESCRIPTOR.message_types_by_name['Step'] = _STEP
DESCRIPTOR.message_types_by_name['Radio'] = _RADIO
DESCRIPTOR.message_types_by_name['Orientation'] = _ORIENTATION
DESCRIPTOR.enum_types_by_name['RadioType'] = _RADIOTYPE
DESCRIPTOR.enum_types_by_name['OrientationType'] = _ORIENTATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR,
  __module__ = 'ips_protocol.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Sensor)
  ))
_sym_db.RegisterMessage(Sensor)

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), dict(
  DESCRIPTOR = _CONTEXT,
  __module__ = 'ips_protocol.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Context)
  ))
_sym_db.RegisterMessage(Context)

Pressure = _reflection.GeneratedProtocolMessageType('Pressure', (_message.Message,), dict(
  DESCRIPTOR = _PRESSURE,
  __module__ = 'ips_protocol.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Pressure)
  ))
_sym_db.RegisterMessage(Pressure)

Step = _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), dict(
  DESCRIPTOR = _STEP,
  __module__ = 'ips_protocol.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Step)
  ))
_sym_db.RegisterMessage(Step)

Radio = _reflection.GeneratedProtocolMessageType('Radio', (_message.Message,), dict(
  DESCRIPTOR = _RADIO,
  __module__ = 'ips_protocol.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Radio)
  ))
_sym_db.RegisterMessage(Radio)

Orientation = _reflection.GeneratedProtocolMessageType('Orientation', (_message.Message,), dict(
  DESCRIPTOR = _ORIENTATION,
  __module__ = 'ips_protocol.sensors_pb2'
  # @@protoc_insertion_point(class_scope:ips.proto.Orientation)
  ))
_sym_db.RegisterMessage(Orientation)


_STEP.fields_by_name['max_acc']._options = None
# @@protoc_insertion_point(module_scope)
